services:
  api:
    build: .
    container_name: smart-oven-api
    restart: unless-stopped
    privileged: true # Give full hardware access
    ports:
      - "8081:8081"
    environment:
      SENSOR_RTD_NOMINAL: "100" # set 1000 for PT1000
      SENSOR_REF_RESISTOR: "430" # adjust to your breakout's value
      SENSOR_WIRES: "3" # 2, 3, or 4
      SENSOR_CS: "CE0" # or CE1 (maps to /dev/spidev0.1)
    devices:
      - /dev/spidev0.0
      - /dev/gpiomem
    # If you ever use CE1 instead:
    # devices:
    #   - /dev/spidev0.1
    #   - /dev/gpiomem
