services:
  api:
    build: .
    container_name: smart-oven-api
    restart: unless-stopped
    privileged: true # Give full hardware access
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
    ports:
      - "8081:8081"
    volumes:
      - /run/udev:/run/udev:ro
    environment:
      SENSOR_RTD_NOMINAL: "100" # set 1000 for PT1000
      SENSOR_REF_RESISTOR: "430" # adjust to your breakout's value
      SENSOR_WIRES: "3" # 2, 3, or 4
