name: Analyze Display Configuration (AFTER)
on:
  workflow_dispatch:
    inputs:
      description:
        description: "What changes did you make?"
        required: false
        default: "Manual display rotation changes"
        type: string
      rotation_working:
        description: "Did the display rotation work?"
        required: true
        default: "yes"
        type: choice
        options:
          - yes
          - no
          - partially

jobs:
  analyze-after:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Display Analysis (AFTER Changes)
        run: |
          echo "=== Display Configuration Analysis (AFTER) ==="
          echo "Description: ${{ github.event.inputs.description }}"
          echo "Rotation working: ${{ github.event.inputs.rotation_working }}"
          echo "Timestamp: $(date)"
          echo ""

          chmod +x deploy/setup-scripts/analyze-display-config-after.sh
          ./deploy/setup-scripts/analyze-display-config-after.sh

      - name: Show Analysis Results
        run: |
          ANALYSIS_DIR=$(ls -td /tmp/display-analysis-* 2>/dev/null | head -1)
          if [ -n "$ANALYSIS_DIR" ]; then
            echo "✅ Analysis completed successfully!"
            echo "📁 Analysis directory: $ANALYSIS_DIR"
            echo ""
            
            # Show comparison report if it exists
            if [ -f "$ANALYSIS_DIR/comparison-report.txt" ]; then
              echo "📋 Comparison Report:"
              cat "$ANALYSIS_DIR/comparison-report.txt"
            else
              echo "❌ Comparison report not found"
            fi
            
            echo ""
            echo "📁 All analysis files:"
            ls -la "$ANALYSIS_DIR"
          else
            echo "❌ Analysis directory not found"
            exit 1
          fi

      - name: Save Analysis Directory Path
        run: |
          ANALYSIS_DIR=$(ls -td /tmp/display-analysis-* 2>/dev/null | head -1)
          if [ -n "$ANALYSIS_DIR" ]; then
            echo "analysis_directory=$ANALYSIS_DIR" >> $GITHUB_OUTPUT
            echo "✅ Analysis directory saved: $ANALYSIS_DIR"
          else
            echo "❌ Could not find analysis directory"
            exit 1
          fi

      - name: Upload Analysis Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: display-analysis-after-${{ github.run_number }}
          path: /tmp/display-analysis-*
          retention-days: 30
          if-no-files-found: error

  comparison:
    runs-on: [self-hosted]
    needs: analyze-after
    steps:
      - name: Detailed Comparison Analysis
        run: |
          ANALYSIS_DIR=$(ls -td /tmp/display-analysis-* 2>/dev/null | head -1)
          if [ -n "$ANALYSIS_DIR" ]; then
            echo "=== Detailed Comparison Analysis ==="
            echo ""
            
            # Check if comparison report exists
            if [ -f "$ANALYSIS_DIR/comparison-report.txt" ]; then
              echo "📋 Full Comparison Report:"
              echo "=========================================="
              cat "$ANALYSIS_DIR/comparison-report.txt"
              echo "=========================================="
            fi
            
            echo ""
            echo "🔍 Key Files Changed:"
            
            # Check each key file for changes
            for file in config.txt cmdline.txt 40-libinput.conf; do
              if [ -f "$ANALYSIS_DIR/${file}.before" ] && [ -f "$ANALYSIS_DIR/${file}.after" ]; then
                if ! diff -q "$ANALYSIS_DIR/${file}.before" "$ANALYSIS_DIR/${file}.after" > /dev/null; then
                  echo "✅ $file - MODIFIED"
                  echo "   Changes:"
                  diff "$ANALYSIS_DIR/${file}.before" "$ANALYSIS_DIR/${file}.after" | sed 's/^/     /'
                  echo ""
                else
                  echo "⏭️  $file - NO CHANGES"
                fi
              else
                echo "❌ $file - NOT FOUND"
              fi
            done
            
            echo ""
            echo "💡 Analysis Summary:"
            echo "  - Rotation working: ${{ github.event.inputs.rotation_working }}"
            echo "  - Analysis directory: $ANALYSIS_DIR"
            echo "  - Comparison report: $ANALYSIS_DIR/comparison-report.txt"
            echo ""
            echo "🔄 Next steps:"
            echo "1. Review the comparison report above"
            echo "2. Share the key changes that made rotation work"
            echo "3. I'll create an automated script based on your findings"
            
          else
            echo "❌ Analysis directory not found"
            exit 1
          fi

  summary:
    runs-on: [self-hosted]
    needs: [analyze-after, comparison]
    steps:
      - name: Final Summary
        run: |
          echo "=== Display Analysis Complete ==="
          echo ""
          echo "✅ AFTER analysis completed successfully!"
          echo ""
          echo "📊 Results:"
          echo "  - Rotation working: ${{ github.event.inputs.rotation_working }}"
          echo "  - Changes analyzed: ✅"
          echo "  - Comparison report: ✅"
          echo ""
          echo "📋 What was analyzed:"
          echo "  - All configuration file changes"
          echo "  - System state differences"
          echo "  - Display status changes"
          echo "  - Environment changes"
          echo ""
          echo "🎯 Key findings:"
          echo "  - See the detailed comparison above"
          echo "  - Look for files marked as 'MODIFIED'"
          echo "  - Focus on config.txt and cmdline.txt changes"
          echo ""
          echo "💡 Share the comparison results with me to create the perfect automated script!"
