name: Analyze Display Configuration (BEFORE)
on:
  workflow_dispatch:
    inputs:
      description:
        description: "What changes are you about to make?"
        required: false
        default: "Manual display rotation changes"
        type: string

jobs:
  analyze-before:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Display Analysis (BEFORE Changes)
        run: |
          echo "=== Display Configuration Analysis (BEFORE) ==="
          echo "Description: ${{ github.event.inputs.description }}"
          echo "Timestamp: $(date)"
          echo ""

          chmod +x deploy/setup-scripts/analyze-display-config.sh
          ./deploy/setup-scripts/analyze-display-config.sh

      - name: Show Analysis Directory
        run: |
          ANALYSIS_DIR=$(ls -td /tmp/display-analysis-* 2>/dev/null | head -1)
          if [ -n "$ANALYSIS_DIR" ]; then
            echo "✅ Analysis completed successfully!"
            echo "📁 Analysis directory: $ANALYSIS_DIR"
            echo ""
            echo "📋 Files saved:"
            ls -la "$ANALYSIS_DIR"
            echo ""
            echo "🔄 Next steps:"
            echo "1. Make your manual display rotation changes"
            echo "2. Run the 'Analyze Display Configuration (AFTER)' workflow"
            echo "3. Compare the results to see what worked"
          else
            echo "❌ Analysis directory not found"
            exit 1
          fi

      - name: Save Analysis Directory Path
        run: |
          ANALYSIS_DIR=$(ls -td /tmp/display-analysis-* 2>/dev/null | head -1)
          if [ -n "$ANALYSIS_DIR" ]; then
            echo "analysis_directory=$ANALYSIS_DIR" >> $GITHUB_OUTPUT
            echo "✅ Analysis directory saved: $ANALYSIS_DIR"
          else
            echo "❌ Could not find analysis directory"
            exit 1
          fi

  summary:
    runs-on: [self-hosted]
    needs: analyze-before
    steps:
      - name: Analysis Summary
        run: |
          echo "=== Display Analysis Summary ==="
          echo ""
          echo "✅ BEFORE analysis completed successfully!"
          echo ""
          echo "📋 What was captured:"
          echo "  - System information (Pi 5, OS, kernel)"
          echo "  - Display hardware (DRM devices, modules)"
          echo "  - Current display status (X11, framebuffer)"
          echo "  - Environment information (desktop, display)"
          echo "  - Boot logs (display-related)"
          echo "  - All configuration files (config.txt, cmdline.txt, X11, etc.)"
          echo ""
          echo "🔄 Next steps:"
          echo "1. Make your manual display rotation changes"
          echo "2. Run the 'Analyze Display Configuration (AFTER)' workflow"
          echo "3. The system will automatically compare before/after"
          echo "4. Share the comparison report to create automated script"
          echo ""
          echo "💡 Tip: Take notes of what manual changes you make!"
