name: Deploy to Raspberry Pi
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Install frontend build
        run: |
          sudo mkdir -p /home/smart-oven/frontend
          sudo cp -r ./frontend/dist/* /home/smart-oven/frontend/

      - name: Install/Update systemd units from repo
        run: |
          # Copy unit files from the repo into systemd dir
          sudo install -m 0644 deploy/systemd/oven-frontend.service /etc/systemd/system/oven-frontend.service
          sudo install -m 0644 deploy/systemd/oven-kiosk.service /etc/systemd/system/oven-kiosk.service
          sudo install -m 0644 deploy/systemd/github-actions-runner.service /etc/systemd/system/github-actions-runner.service
          # Pick chromium path if different:
          if [ -x /usr/bin/chromium ] && ! grep -q '/usr/bin/chromium ' /etc/systemd/system/oven-kiosk.service; then
            echo "Warning: chromium path might be /usr/bin/chromium on this system."
          fi
          # Reload & enable services
          sudo systemctl daemon-reload
          sudo systemctl enable oven-frontend.service
          sudo systemctl enable oven-kiosk.service
          sudo systemctl enable github-actions-runner.service

      - name: Ensure static server is available (once)
        run: |
          if ! command -v serve >/dev/null 2>&1; then
            sudo npm i -g serve
          fi

      - name: Restart services
        run: |
          sudo systemctl restart oven-frontend.service
          # small delay so :3000 is up before kiosk launches
          sleep 2
          sudo systemctl restart oven-kiosk.service
          sudo systemctl restart github-actions-runner.service

      - name: Restart Raspberry Pi
        run: |
          exit 0  # Mark job as complete
          sudo reboot  # Reboot happens after the action finishes

