name: Deploy to Raspberry Pi
on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "deploy/systemd/**"
      - "api/**"
      - ".github/workflows/deploy-pi.yml"
      - ".github/actions/**"

jobs:
  frontend:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Convex and generate API
        working-directory: ./db
        run: |
          npm ci
          npx convex dev --once || npx convex codegen

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Install frontend build
        run: |
          sudo mkdir -p /home/smart-oven/frontend
          sudo cp -r ./frontend/dist/* /home/smart-oven/frontend/

  systemd:
    runs-on: [self-hosted]
    steps:
      - name: Install/Update systemd units from repo
        run: |
          # Copy unit files from the repo into systemd dir
          sudo install -m 0644 deploy/systemd/smart-oven-api.service /etc/systemd/system/smart-oven-api.service
          sudo install -m 0644 deploy/systemd/smart-oven-web.service /etc/systemd/system/smart-oven-web.service
          sudo install -m 0644 deploy/systemd/smart-oven-display.service /etc/systemd/system/smart-oven-display.service
          sudo install -m 0644 deploy/systemd/github-runner.service /etc/systemd/system/github-runner.service

          # Pick chromium path if different:
          if [ -x /usr/bin/chromium ] && ! grep -q '/usr/bin/chromium ' /etc/systemd/system/smart-oven-display.service; then
            echo "Warning: chromium path might be /usr/bin/chromium on this system."
          fi

          # Reload & enable services
          sudo systemctl daemon-reload
          sudo systemctl enable smart-oven-api.service
          sudo systemctl enable smart-oven-web.service
          sudo systemctl enable smart-oven-display.service
          sudo systemctl enable github-runner.service

  api:
    runs-on: [self-hosted]
    steps:
      - name: Restart API
        working-directory: ./api
        run: |
          docker compose down || true
          docker compose up -d --build

      - name: Wait for container to start
        run: |
          sleep 10

      - name: Show API logs
        working-directory: ./api
        run: |
          echo "=== API Container Logs ==="
          docker compose logs --tail=50 api || echo "Could not retrieve logs"
          echo "=== End API Container Logs ==="

      - name: Smoke test
        run: |
          curl -sSf http://127.0.0.1:8081/health

      - name: Display API endpoints
        run: |
          # Get Pi's IP address
          PI_IP=$(hostname -I | awk '{print $1}')

          echo "=========================================="
          echo "API is now accessible from external devices:"
          echo "http://$PI_IP:8081/"
          echo "=========================================="

  reboot:
    runs-on: [self-hosted]
    needs: [frontend, systemd, api]
    if: always() && needs.systemd.result == 'success'
    continue-on-error: true # Allow failure on this job
    timeout-minutes: 1 # Prevent hanging indefinitely
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Reboot Raspberry Pi
        uses: ./.github/actions/reboot-pi
        with:
          reason: "Systemd configuration changed. Rebooting Pi to restart all services with new configs."
          wait_seconds: "10"
