name: Setup Raspberry Pi
on:
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: [self-hosted]
    outputs:
      needs-reboot: ${{ steps.check-reboot.outputs.needs-reboot }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check current system and SPI status
        run: |
          chmod +x deploy/setup-scripts/check-system.sh
          ./deploy/setup-scripts/check-system.sh

      - name: Install Docker
        run: |
          chmod +x deploy/setup-scripts/install-docker.sh
          ./deploy/setup-scripts/install-docker.sh

      - name: Enable SPI interface
        id: enable-spi
        run: |
          chmod +x deploy/setup-scripts/enable-spi.sh
          ./deploy/setup-scripts/enable-spi.sh

      - name: Enable I2C interface (optional, for future use)
        id: enable-i2c
        run: |
          chmod +x deploy/setup-scripts/enable-i2c.sh
          ./deploy/setup-scripts/enable-i2c.sh

      - name: Verify configuration changes
        run: |
          chmod +x deploy/setup-scripts/verify-config.sh
          ./deploy/setup-scripts/verify-config.sh

      - name: Determine if reboot is needed
        id: check-reboot
        run: |
          chmod +x deploy/setup-scripts/check-reboot.sh
          ./deploy/setup-scripts/check-reboot.sh

      - name: Setup summary
        run: |
          chmod +x deploy/setup-scripts/setup-summary.sh
          ./deploy/setup-scripts/setup-summary.sh

  reboot:
    runs-on: [self-hosted]
    needs: bootstrap
    if: needs.bootstrap.outputs.needs-reboot == 'true'
    continue-on-error: true
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Reboot Raspberry Pi
        uses: ./.github/actions/reboot-pi
        with:
          reason: "Hardware interfaces (SPI/I2C) were enabled. Rebooting to activate them."
          wait_seconds: "5"
